/**
 *
 *  BillingLedger.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace WssdApi
{

class BillingLedger
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _business_subscription_id;
        static const std::string _ussd_session_id;
        static const std::string _transaction_type;
        static const std::string _amount;
        static const std::string _is_credit;
        static const std::string _balance_before;
        static const std::string _balance_after;
        static const std::string _description;
        static const std::string _reference_code;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit BillingLedger(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit BillingLedger(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    BillingLedger(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    BillingLedger() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column business_subscription_id  */
    ///Get the value of the column business_subscription_id, returns the default value if the column is null
    const std::string &getValueOfBusinessSubscriptionId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBusinessSubscriptionId() const noexcept;
    ///Set the value of the column business_subscription_id
    void setBusinessSubscriptionId(const std::string &pBusinessSubscriptionId) noexcept;
    void setBusinessSubscriptionId(std::string &&pBusinessSubscriptionId) noexcept;

    /**  For column ussd_session_id  */
    ///Get the value of the column ussd_session_id, returns the default value if the column is null
    const std::string &getValueOfUssdSessionId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUssdSessionId() const noexcept;
    ///Set the value of the column ussd_session_id
    void setUssdSessionId(const std::string &pUssdSessionId) noexcept;
    void setUssdSessionId(std::string &&pUssdSessionId) noexcept;
    void setUssdSessionIdToNull() noexcept;

    /**  For column transaction_type  */
    ///Get the value of the column transaction_type, returns the default value if the column is null
    const std::string &getValueOfTransactionType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTransactionType() const noexcept;
    ///Set the value of the column transaction_type
    void setTransactionType(const std::string &pTransactionType) noexcept;
    void setTransactionType(std::string &&pTransactionType) noexcept;

    /**  For column amount  */
    ///Get the value of the column amount, returns the default value if the column is null
    const std::string &getValueOfAmount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAmount() const noexcept;
    ///Set the value of the column amount
    void setAmount(const std::string &pAmount) noexcept;
    void setAmount(std::string &&pAmount) noexcept;

    /**  For column is_credit  */
    ///Get the value of the column is_credit, returns the default value if the column is null
    const bool &getValueOfIsCredit() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsCredit() const noexcept;
    ///Set the value of the column is_credit
    void setIsCredit(const bool &pIsCredit) noexcept;

    /**  For column balance_before  */
    ///Get the value of the column balance_before, returns the default value if the column is null
    const std::string &getValueOfBalanceBefore() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBalanceBefore() const noexcept;
    ///Set the value of the column balance_before
    void setBalanceBefore(const std::string &pBalanceBefore) noexcept;
    void setBalanceBefore(std::string &&pBalanceBefore) noexcept;

    /**  For column balance_after  */
    ///Get the value of the column balance_after, returns the default value if the column is null
    const std::string &getValueOfBalanceAfter() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBalanceAfter() const noexcept;
    ///Set the value of the column balance_after
    void setBalanceAfter(const std::string &pBalanceAfter) noexcept;
    void setBalanceAfter(std::string &&pBalanceAfter) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column reference_code  */
    ///Get the value of the column reference_code, returns the default value if the column is null
    const std::string &getValueOfReferenceCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReferenceCode() const noexcept;
    ///Set the value of the column reference_code
    void setReferenceCode(const std::string &pReferenceCode) noexcept;
    void setReferenceCode(std::string &&pReferenceCode) noexcept;
    void setReferenceCodeToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 11;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<BillingLedger>;
    friend drogon::orm::BaseBuilder<BillingLedger, true, true>;
    friend drogon::orm::BaseBuilder<BillingLedger, true, false>;
    friend drogon::orm::BaseBuilder<BillingLedger, false, true>;
    friend drogon::orm::BaseBuilder<BillingLedger, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<BillingLedger>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> businessSubscriptionId_;
    std::shared_ptr<std::string> ussdSessionId_;
    std::shared_ptr<std::string> transactionType_;
    std::shared_ptr<std::string> amount_;
    std::shared_ptr<bool> isCredit_;
    std::shared_ptr<std::string> balanceBefore_;
    std::shared_ptr<std::string> balanceAfter_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> referenceCode_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "business_subscription_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "ussd_session_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "transaction_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "amount,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "is_credit,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "balance_before,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "balance_after,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "reference_code,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace WssdApi
} // namespace drogon_model
