/**
 *
 *  SubscriptionRenewalHistory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "SubscriptionRenewalHistory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::WssdApi;

const std::string SubscriptionRenewalHistory::Cols::_id = "\"id\"";
const std::string SubscriptionRenewalHistory::Cols::_business_subscription_id = "\"business_subscription_id\"";
const std::string SubscriptionRenewalHistory::Cols::_service_type = "\"service_type\"";
const std::string SubscriptionRenewalHistory::Cols::_renewal_date = "\"renewal_date\"";
const std::string SubscriptionRenewalHistory::Cols::_previous_end_date = "\"previous_end_date\"";
const std::string SubscriptionRenewalHistory::Cols::_new_end_date = "\"new_end_date\"";
const std::string SubscriptionRenewalHistory::Cols::_amount_paid = "\"amount_paid\"";
const std::string SubscriptionRenewalHistory::Cols::_currency = "\"currency\"";
const std::string SubscriptionRenewalHistory::Cols::_payment_reference = "\"payment_reference\"";
const std::string SubscriptionRenewalHistory::Cols::_renewal_status = "\"renewal_status\"";
const std::string SubscriptionRenewalHistory::Cols::_renewal_method = "\"renewal_method\"";
const std::string SubscriptionRenewalHistory::Cols::_remarks = "\"remarks\"";
const std::string SubscriptionRenewalHistory::Cols::_created_at = "\"created_at\"";
const std::string SubscriptionRenewalHistory::primaryKeyName = "id";
const bool SubscriptionRenewalHistory::hasPrimaryKey = true;
const std::string SubscriptionRenewalHistory::tableName = "\"subscription_renewal_history\"";

const std::vector<typename SubscriptionRenewalHistory::MetaData> SubscriptionRenewalHistory::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"business_subscription_id","std::string","uuid",0,0,0,1},
{"service_type","std::string","character varying",20,0,0,1},
{"renewal_date","::trantor::Date","timestamp with time zone",0,0,0,0},
{"previous_end_date","::trantor::Date","timestamp with time zone",0,0,0,0},
{"new_end_date","::trantor::Date","timestamp with time zone",0,0,0,1},
{"amount_paid","std::string","numeric",0,0,0,1},
{"currency","std::string","character varying",10,0,0,0},
{"payment_reference","std::string","character varying",100,0,0,0},
{"renewal_status","std::string","character varying",20,0,0,0},
{"renewal_method","std::string","character varying",50,0,0,0},
{"remarks","std::string","text",0,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &SubscriptionRenewalHistory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
SubscriptionRenewalHistory::SubscriptionRenewalHistory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["business_subscription_id"].isNull())
        {
            businessSubscriptionId_=std::make_shared<std::string>(r["business_subscription_id"].as<std::string>());
        }
        if(!r["service_type"].isNull())
        {
            serviceType_=std::make_shared<std::string>(r["service_type"].as<std::string>());
        }
        if(!r["renewal_date"].isNull())
        {
            auto timeStr = r["renewal_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                renewalDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["previous_end_date"].isNull())
        {
            auto timeStr = r["previous_end_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                previousEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["new_end_date"].isNull())
        {
            auto timeStr = r["new_end_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                newEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["amount_paid"].isNull())
        {
            amountPaid_=std::make_shared<std::string>(r["amount_paid"].as<std::string>());
        }
        if(!r["currency"].isNull())
        {
            currency_=std::make_shared<std::string>(r["currency"].as<std::string>());
        }
        if(!r["payment_reference"].isNull())
        {
            paymentReference_=std::make_shared<std::string>(r["payment_reference"].as<std::string>());
        }
        if(!r["renewal_status"].isNull())
        {
            renewalStatus_=std::make_shared<std::string>(r["renewal_status"].as<std::string>());
        }
        if(!r["renewal_method"].isNull())
        {
            renewalMethod_=std::make_shared<std::string>(r["renewal_method"].as<std::string>());
        }
        if(!r["remarks"].isNull())
        {
            remarks_=std::make_shared<std::string>(r["remarks"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            businessSubscriptionId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            serviceType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                renewalDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                previousEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                newEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            amountPaid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            currency_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            paymentReference_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            renewalStatus_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            renewalMethod_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            remarks_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

SubscriptionRenewalHistory::SubscriptionRenewalHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            businessSubscriptionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            serviceType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                renewalDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                previousEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                newEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            amountPaid_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            currency_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            paymentReference_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            renewalStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            renewalMethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            remarks_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

SubscriptionRenewalHistory::SubscriptionRenewalHistory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("business_subscription_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["business_subscription_id"].isNull())
        {
            businessSubscriptionId_=std::make_shared<std::string>(pJson["business_subscription_id"].asString());
        }
    }
    if(pJson.isMember("service_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["service_type"].isNull())
        {
            serviceType_=std::make_shared<std::string>(pJson["service_type"].asString());
        }
    }
    if(pJson.isMember("renewal_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["renewal_date"].isNull())
        {
            auto timeStr = pJson["renewal_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                renewalDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("previous_end_date"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["previous_end_date"].isNull())
        {
            auto timeStr = pJson["previous_end_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                previousEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("new_end_date"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["new_end_date"].isNull())
        {
            auto timeStr = pJson["new_end_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                newEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("amount_paid"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["amount_paid"].isNull())
        {
            amountPaid_=std::make_shared<std::string>(pJson["amount_paid"].asString());
        }
    }
    if(pJson.isMember("currency"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["currency"].isNull())
        {
            currency_=std::make_shared<std::string>(pJson["currency"].asString());
        }
    }
    if(pJson.isMember("payment_reference"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["payment_reference"].isNull())
        {
            paymentReference_=std::make_shared<std::string>(pJson["payment_reference"].asString());
        }
    }
    if(pJson.isMember("renewal_status"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["renewal_status"].isNull())
        {
            renewalStatus_=std::make_shared<std::string>(pJson["renewal_status"].asString());
        }
    }
    if(pJson.isMember("renewal_method"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["renewal_method"].isNull())
        {
            renewalMethod_=std::make_shared<std::string>(pJson["renewal_method"].asString());
        }
    }
    if(pJson.isMember("remarks"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["remarks"].isNull())
        {
            remarks_=std::make_shared<std::string>(pJson["remarks"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void SubscriptionRenewalHistory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            businessSubscriptionId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            serviceType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                renewalDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                previousEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                newEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            amountPaid_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            currency_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            paymentReference_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            renewalStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            renewalMethod_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            remarks_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void SubscriptionRenewalHistory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("business_subscription_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["business_subscription_id"].isNull())
        {
            businessSubscriptionId_=std::make_shared<std::string>(pJson["business_subscription_id"].asString());
        }
    }
    if(pJson.isMember("service_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["service_type"].isNull())
        {
            serviceType_=std::make_shared<std::string>(pJson["service_type"].asString());
        }
    }
    if(pJson.isMember("renewal_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["renewal_date"].isNull())
        {
            auto timeStr = pJson["renewal_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                renewalDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("previous_end_date"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["previous_end_date"].isNull())
        {
            auto timeStr = pJson["previous_end_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                previousEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("new_end_date"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["new_end_date"].isNull())
        {
            auto timeStr = pJson["new_end_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                newEndDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("amount_paid"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["amount_paid"].isNull())
        {
            amountPaid_=std::make_shared<std::string>(pJson["amount_paid"].asString());
        }
    }
    if(pJson.isMember("currency"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["currency"].isNull())
        {
            currency_=std::make_shared<std::string>(pJson["currency"].asString());
        }
    }
    if(pJson.isMember("payment_reference"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["payment_reference"].isNull())
        {
            paymentReference_=std::make_shared<std::string>(pJson["payment_reference"].asString());
        }
    }
    if(pJson.isMember("renewal_status"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["renewal_status"].isNull())
        {
            renewalStatus_=std::make_shared<std::string>(pJson["renewal_status"].asString());
        }
    }
    if(pJson.isMember("renewal_method"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["renewal_method"].isNull())
        {
            renewalMethod_=std::make_shared<std::string>(pJson["renewal_method"].asString());
        }
    }
    if(pJson.isMember("remarks"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["remarks"].isNull())
        {
            remarks_=std::make_shared<std::string>(pJson["remarks"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &SubscriptionRenewalHistory::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getId() const noexcept
{
    return id_;
}
void SubscriptionRenewalHistory::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void SubscriptionRenewalHistory::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename SubscriptionRenewalHistory::PrimaryKeyType & SubscriptionRenewalHistory::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &SubscriptionRenewalHistory::getValueOfBusinessSubscriptionId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(businessSubscriptionId_)
        return *businessSubscriptionId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getBusinessSubscriptionId() const noexcept
{
    return businessSubscriptionId_;
}
void SubscriptionRenewalHistory::setBusinessSubscriptionId(const std::string &pBusinessSubscriptionId) noexcept
{
    businessSubscriptionId_ = std::make_shared<std::string>(pBusinessSubscriptionId);
    dirtyFlag_[1] = true;
}
void SubscriptionRenewalHistory::setBusinessSubscriptionId(std::string &&pBusinessSubscriptionId) noexcept
{
    businessSubscriptionId_ = std::make_shared<std::string>(std::move(pBusinessSubscriptionId));
    dirtyFlag_[1] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfServiceType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(serviceType_)
        return *serviceType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getServiceType() const noexcept
{
    return serviceType_;
}
void SubscriptionRenewalHistory::setServiceType(const std::string &pServiceType) noexcept
{
    serviceType_ = std::make_shared<std::string>(pServiceType);
    dirtyFlag_[2] = true;
}
void SubscriptionRenewalHistory::setServiceType(std::string &&pServiceType) noexcept
{
    serviceType_ = std::make_shared<std::string>(std::move(pServiceType));
    dirtyFlag_[2] = true;
}

const ::trantor::Date &SubscriptionRenewalHistory::getValueOfRenewalDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(renewalDate_)
        return *renewalDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SubscriptionRenewalHistory::getRenewalDate() const noexcept
{
    return renewalDate_;
}
void SubscriptionRenewalHistory::setRenewalDate(const ::trantor::Date &pRenewalDate) noexcept
{
    renewalDate_ = std::make_shared<::trantor::Date>(pRenewalDate);
    dirtyFlag_[3] = true;
}
void SubscriptionRenewalHistory::setRenewalDateToNull() noexcept
{
    renewalDate_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &SubscriptionRenewalHistory::getValueOfPreviousEndDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(previousEndDate_)
        return *previousEndDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SubscriptionRenewalHistory::getPreviousEndDate() const noexcept
{
    return previousEndDate_;
}
void SubscriptionRenewalHistory::setPreviousEndDate(const ::trantor::Date &pPreviousEndDate) noexcept
{
    previousEndDate_ = std::make_shared<::trantor::Date>(pPreviousEndDate);
    dirtyFlag_[4] = true;
}
void SubscriptionRenewalHistory::setPreviousEndDateToNull() noexcept
{
    previousEndDate_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &SubscriptionRenewalHistory::getValueOfNewEndDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(newEndDate_)
        return *newEndDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SubscriptionRenewalHistory::getNewEndDate() const noexcept
{
    return newEndDate_;
}
void SubscriptionRenewalHistory::setNewEndDate(const ::trantor::Date &pNewEndDate) noexcept
{
    newEndDate_ = std::make_shared<::trantor::Date>(pNewEndDate);
    dirtyFlag_[5] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfAmountPaid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(amountPaid_)
        return *amountPaid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getAmountPaid() const noexcept
{
    return amountPaid_;
}
void SubscriptionRenewalHistory::setAmountPaid(const std::string &pAmountPaid) noexcept
{
    amountPaid_ = std::make_shared<std::string>(pAmountPaid);
    dirtyFlag_[6] = true;
}
void SubscriptionRenewalHistory::setAmountPaid(std::string &&pAmountPaid) noexcept
{
    amountPaid_ = std::make_shared<std::string>(std::move(pAmountPaid));
    dirtyFlag_[6] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfCurrency() const noexcept
{
    static const std::string defaultValue = std::string();
    if(currency_)
        return *currency_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getCurrency() const noexcept
{
    return currency_;
}
void SubscriptionRenewalHistory::setCurrency(const std::string &pCurrency) noexcept
{
    currency_ = std::make_shared<std::string>(pCurrency);
    dirtyFlag_[7] = true;
}
void SubscriptionRenewalHistory::setCurrency(std::string &&pCurrency) noexcept
{
    currency_ = std::make_shared<std::string>(std::move(pCurrency));
    dirtyFlag_[7] = true;
}
void SubscriptionRenewalHistory::setCurrencyToNull() noexcept
{
    currency_.reset();
    dirtyFlag_[7] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfPaymentReference() const noexcept
{
    static const std::string defaultValue = std::string();
    if(paymentReference_)
        return *paymentReference_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getPaymentReference() const noexcept
{
    return paymentReference_;
}
void SubscriptionRenewalHistory::setPaymentReference(const std::string &pPaymentReference) noexcept
{
    paymentReference_ = std::make_shared<std::string>(pPaymentReference);
    dirtyFlag_[8] = true;
}
void SubscriptionRenewalHistory::setPaymentReference(std::string &&pPaymentReference) noexcept
{
    paymentReference_ = std::make_shared<std::string>(std::move(pPaymentReference));
    dirtyFlag_[8] = true;
}
void SubscriptionRenewalHistory::setPaymentReferenceToNull() noexcept
{
    paymentReference_.reset();
    dirtyFlag_[8] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfRenewalStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(renewalStatus_)
        return *renewalStatus_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getRenewalStatus() const noexcept
{
    return renewalStatus_;
}
void SubscriptionRenewalHistory::setRenewalStatus(const std::string &pRenewalStatus) noexcept
{
    renewalStatus_ = std::make_shared<std::string>(pRenewalStatus);
    dirtyFlag_[9] = true;
}
void SubscriptionRenewalHistory::setRenewalStatus(std::string &&pRenewalStatus) noexcept
{
    renewalStatus_ = std::make_shared<std::string>(std::move(pRenewalStatus));
    dirtyFlag_[9] = true;
}
void SubscriptionRenewalHistory::setRenewalStatusToNull() noexcept
{
    renewalStatus_.reset();
    dirtyFlag_[9] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfRenewalMethod() const noexcept
{
    static const std::string defaultValue = std::string();
    if(renewalMethod_)
        return *renewalMethod_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getRenewalMethod() const noexcept
{
    return renewalMethod_;
}
void SubscriptionRenewalHistory::setRenewalMethod(const std::string &pRenewalMethod) noexcept
{
    renewalMethod_ = std::make_shared<std::string>(pRenewalMethod);
    dirtyFlag_[10] = true;
}
void SubscriptionRenewalHistory::setRenewalMethod(std::string &&pRenewalMethod) noexcept
{
    renewalMethod_ = std::make_shared<std::string>(std::move(pRenewalMethod));
    dirtyFlag_[10] = true;
}
void SubscriptionRenewalHistory::setRenewalMethodToNull() noexcept
{
    renewalMethod_.reset();
    dirtyFlag_[10] = true;
}

const std::string &SubscriptionRenewalHistory::getValueOfRemarks() const noexcept
{
    static const std::string defaultValue = std::string();
    if(remarks_)
        return *remarks_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SubscriptionRenewalHistory::getRemarks() const noexcept
{
    return remarks_;
}
void SubscriptionRenewalHistory::setRemarks(const std::string &pRemarks) noexcept
{
    remarks_ = std::make_shared<std::string>(pRemarks);
    dirtyFlag_[11] = true;
}
void SubscriptionRenewalHistory::setRemarks(std::string &&pRemarks) noexcept
{
    remarks_ = std::make_shared<std::string>(std::move(pRemarks));
    dirtyFlag_[11] = true;
}
void SubscriptionRenewalHistory::setRemarksToNull() noexcept
{
    remarks_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &SubscriptionRenewalHistory::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SubscriptionRenewalHistory::getCreatedAt() const noexcept
{
    return createdAt_;
}
void SubscriptionRenewalHistory::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[12] = true;
}
void SubscriptionRenewalHistory::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[12] = true;
}

void SubscriptionRenewalHistory::updateId(const uint64_t id)
{
}

const std::vector<std::string> &SubscriptionRenewalHistory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "business_subscription_id",
        "service_type",
        "renewal_date",
        "previous_end_date",
        "new_end_date",
        "amount_paid",
        "currency",
        "payment_reference",
        "renewal_status",
        "renewal_method",
        "remarks",
        "created_at"
    };
    return inCols;
}

void SubscriptionRenewalHistory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusinessSubscriptionId())
        {
            binder << getValueOfBusinessSubscriptionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getServiceType())
        {
            binder << getValueOfServiceType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRenewalDate())
        {
            binder << getValueOfRenewalDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPreviousEndDate())
        {
            binder << getValueOfPreviousEndDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getNewEndDate())
        {
            binder << getValueOfNewEndDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAmountPaid())
        {
            binder << getValueOfAmountPaid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCurrency())
        {
            binder << getValueOfCurrency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getPaymentReference())
        {
            binder << getValueOfPaymentReference();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getRenewalStatus())
        {
            binder << getValueOfRenewalStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getRenewalMethod())
        {
            binder << getValueOfRenewalMethod();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getRemarks())
        {
            binder << getValueOfRemarks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> SubscriptionRenewalHistory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void SubscriptionRenewalHistory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusinessSubscriptionId())
        {
            binder << getValueOfBusinessSubscriptionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getServiceType())
        {
            binder << getValueOfServiceType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRenewalDate())
        {
            binder << getValueOfRenewalDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPreviousEndDate())
        {
            binder << getValueOfPreviousEndDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getNewEndDate())
        {
            binder << getValueOfNewEndDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAmountPaid())
        {
            binder << getValueOfAmountPaid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCurrency())
        {
            binder << getValueOfCurrency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getPaymentReference())
        {
            binder << getValueOfPaymentReference();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getRenewalStatus())
        {
            binder << getValueOfRenewalStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getRenewalMethod())
        {
            binder << getValueOfRenewalMethod();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getRemarks())
        {
            binder << getValueOfRemarks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value SubscriptionRenewalHistory::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusinessSubscriptionId())
    {
        ret["business_subscription_id"]=getValueOfBusinessSubscriptionId();
    }
    else
    {
        ret["business_subscription_id"]=Json::Value();
    }
    if(getServiceType())
    {
        ret["service_type"]=getValueOfServiceType();
    }
    else
    {
        ret["service_type"]=Json::Value();
    }
    if(getRenewalDate())
    {
        ret["renewal_date"]=getRenewalDate()->toDbStringLocal();
    }
    else
    {
        ret["renewal_date"]=Json::Value();
    }
    if(getPreviousEndDate())
    {
        ret["previous_end_date"]=getPreviousEndDate()->toDbStringLocal();
    }
    else
    {
        ret["previous_end_date"]=Json::Value();
    }
    if(getNewEndDate())
    {
        ret["new_end_date"]=getNewEndDate()->toDbStringLocal();
    }
    else
    {
        ret["new_end_date"]=Json::Value();
    }
    if(getAmountPaid())
    {
        ret["amount_paid"]=getValueOfAmountPaid();
    }
    else
    {
        ret["amount_paid"]=Json::Value();
    }
    if(getCurrency())
    {
        ret["currency"]=getValueOfCurrency();
    }
    else
    {
        ret["currency"]=Json::Value();
    }
    if(getPaymentReference())
    {
        ret["payment_reference"]=getValueOfPaymentReference();
    }
    else
    {
        ret["payment_reference"]=Json::Value();
    }
    if(getRenewalStatus())
    {
        ret["renewal_status"]=getValueOfRenewalStatus();
    }
    else
    {
        ret["renewal_status"]=Json::Value();
    }
    if(getRenewalMethod())
    {
        ret["renewal_method"]=getValueOfRenewalMethod();
    }
    else
    {
        ret["renewal_method"]=Json::Value();
    }
    if(getRemarks())
    {
        ret["remarks"]=getValueOfRemarks();
    }
    else
    {
        ret["remarks"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string SubscriptionRenewalHistory::toString() const
{
    return toJson().toStyledString();
}

Json::Value SubscriptionRenewalHistory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getBusinessSubscriptionId())
            {
                ret[pMasqueradingVector[1]]=getValueOfBusinessSubscriptionId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getServiceType())
            {
                ret[pMasqueradingVector[2]]=getValueOfServiceType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRenewalDate())
            {
                ret[pMasqueradingVector[3]]=getRenewalDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPreviousEndDate())
            {
                ret[pMasqueradingVector[4]]=getPreviousEndDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getNewEndDate())
            {
                ret[pMasqueradingVector[5]]=getNewEndDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getAmountPaid())
            {
                ret[pMasqueradingVector[6]]=getValueOfAmountPaid();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCurrency())
            {
                ret[pMasqueradingVector[7]]=getValueOfCurrency();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getPaymentReference())
            {
                ret[pMasqueradingVector[8]]=getValueOfPaymentReference();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getRenewalStatus())
            {
                ret[pMasqueradingVector[9]]=getValueOfRenewalStatus();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getRenewalMethod())
            {
                ret[pMasqueradingVector[10]]=getValueOfRenewalMethod();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getRemarks())
            {
                ret[pMasqueradingVector[11]]=getValueOfRemarks();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[12]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusinessSubscriptionId())
    {
        ret["business_subscription_id"]=getValueOfBusinessSubscriptionId();
    }
    else
    {
        ret["business_subscription_id"]=Json::Value();
    }
    if(getServiceType())
    {
        ret["service_type"]=getValueOfServiceType();
    }
    else
    {
        ret["service_type"]=Json::Value();
    }
    if(getRenewalDate())
    {
        ret["renewal_date"]=getRenewalDate()->toDbStringLocal();
    }
    else
    {
        ret["renewal_date"]=Json::Value();
    }
    if(getPreviousEndDate())
    {
        ret["previous_end_date"]=getPreviousEndDate()->toDbStringLocal();
    }
    else
    {
        ret["previous_end_date"]=Json::Value();
    }
    if(getNewEndDate())
    {
        ret["new_end_date"]=getNewEndDate()->toDbStringLocal();
    }
    else
    {
        ret["new_end_date"]=Json::Value();
    }
    if(getAmountPaid())
    {
        ret["amount_paid"]=getValueOfAmountPaid();
    }
    else
    {
        ret["amount_paid"]=Json::Value();
    }
    if(getCurrency())
    {
        ret["currency"]=getValueOfCurrency();
    }
    else
    {
        ret["currency"]=Json::Value();
    }
    if(getPaymentReference())
    {
        ret["payment_reference"]=getValueOfPaymentReference();
    }
    else
    {
        ret["payment_reference"]=Json::Value();
    }
    if(getRenewalStatus())
    {
        ret["renewal_status"]=getValueOfRenewalStatus();
    }
    else
    {
        ret["renewal_status"]=Json::Value();
    }
    if(getRenewalMethod())
    {
        ret["renewal_method"]=getValueOfRenewalMethod();
    }
    else
    {
        ret["renewal_method"]=Json::Value();
    }
    if(getRemarks())
    {
        ret["remarks"]=getValueOfRemarks();
    }
    else
    {
        ret["remarks"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool SubscriptionRenewalHistory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("business_subscription_id"))
    {
        if(!validJsonOfField(1, "business_subscription_id", pJson["business_subscription_id"], err, true))
            return false;
    }
    else
    {
        err="The business_subscription_id column cannot be null";
        return false;
    }
    if(pJson.isMember("service_type"))
    {
        if(!validJsonOfField(2, "service_type", pJson["service_type"], err, true))
            return false;
    }
    else
    {
        err="The service_type column cannot be null";
        return false;
    }
    if(pJson.isMember("renewal_date"))
    {
        if(!validJsonOfField(3, "renewal_date", pJson["renewal_date"], err, true))
            return false;
    }
    if(pJson.isMember("previous_end_date"))
    {
        if(!validJsonOfField(4, "previous_end_date", pJson["previous_end_date"], err, true))
            return false;
    }
    if(pJson.isMember("new_end_date"))
    {
        if(!validJsonOfField(5, "new_end_date", pJson["new_end_date"], err, true))
            return false;
    }
    else
    {
        err="The new_end_date column cannot be null";
        return false;
    }
    if(pJson.isMember("amount_paid"))
    {
        if(!validJsonOfField(6, "amount_paid", pJson["amount_paid"], err, true))
            return false;
    }
    if(pJson.isMember("currency"))
    {
        if(!validJsonOfField(7, "currency", pJson["currency"], err, true))
            return false;
    }
    if(pJson.isMember("payment_reference"))
    {
        if(!validJsonOfField(8, "payment_reference", pJson["payment_reference"], err, true))
            return false;
    }
    if(pJson.isMember("renewal_status"))
    {
        if(!validJsonOfField(9, "renewal_status", pJson["renewal_status"], err, true))
            return false;
    }
    if(pJson.isMember("renewal_method"))
    {
        if(!validJsonOfField(10, "renewal_method", pJson["renewal_method"], err, true))
            return false;
    }
    if(pJson.isMember("remarks"))
    {
        if(!validJsonOfField(11, "remarks", pJson["remarks"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(12, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool SubscriptionRenewalHistory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                    const std::vector<std::string> &pMasqueradingVector,
                                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SubscriptionRenewalHistory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("business_subscription_id"))
    {
        if(!validJsonOfField(1, "business_subscription_id", pJson["business_subscription_id"], err, false))
            return false;
    }
    if(pJson.isMember("service_type"))
    {
        if(!validJsonOfField(2, "service_type", pJson["service_type"], err, false))
            return false;
    }
    if(pJson.isMember("renewal_date"))
    {
        if(!validJsonOfField(3, "renewal_date", pJson["renewal_date"], err, false))
            return false;
    }
    if(pJson.isMember("previous_end_date"))
    {
        if(!validJsonOfField(4, "previous_end_date", pJson["previous_end_date"], err, false))
            return false;
    }
    if(pJson.isMember("new_end_date"))
    {
        if(!validJsonOfField(5, "new_end_date", pJson["new_end_date"], err, false))
            return false;
    }
    if(pJson.isMember("amount_paid"))
    {
        if(!validJsonOfField(6, "amount_paid", pJson["amount_paid"], err, false))
            return false;
    }
    if(pJson.isMember("currency"))
    {
        if(!validJsonOfField(7, "currency", pJson["currency"], err, false))
            return false;
    }
    if(pJson.isMember("payment_reference"))
    {
        if(!validJsonOfField(8, "payment_reference", pJson["payment_reference"], err, false))
            return false;
    }
    if(pJson.isMember("renewal_status"))
    {
        if(!validJsonOfField(9, "renewal_status", pJson["renewal_status"], err, false))
            return false;
    }
    if(pJson.isMember("renewal_method"))
    {
        if(!validJsonOfField(10, "renewal_method", pJson["renewal_method"], err, false))
            return false;
    }
    if(pJson.isMember("remarks"))
    {
        if(!validJsonOfField(11, "remarks", pJson["remarks"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(12, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool SubscriptionRenewalHistory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                  const std::vector<std::string> &pMasqueradingVector,
                                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SubscriptionRenewalHistory::validJsonOfField(size_t index,
                                                  const std::string &fieldName,
                                                  const Json::Value &pJson,
                                                  std::string &err,
                                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
