/**
 *
 *  UssdDirectory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UssdDirectory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::WssdApi;

const std::string UssdDirectory::Cols::_id = "\"id\"";
const std::string UssdDirectory::Cols::_trade_name = "\"trade_name\"";
const std::string UssdDirectory::Cols::_ussd_code = "\"ussd_code\"";
const std::string UssdDirectory::Cols::_business_name = "\"business_name\"";
const std::string UssdDirectory::Cols::_description = "\"description\"";
const std::string UssdDirectory::Cols::_country_code = "\"country_code\"";
const std::string UssdDirectory::Cols::_category = "\"category\"";
const std::string UssdDirectory::Cols::_keywords = "\"keywords\"";
const std::string UssdDirectory::Cols::_is_dedicated = "\"is_dedicated\"";
const std::string UssdDirectory::Cols::_is_wssd_linked = "\"is_wssd_linked\"";
const std::string UssdDirectory::Cols::_rating = "\"rating\"";
const std::string UssdDirectory::Cols::_created_at = "\"created_at\"";
const std::string UssdDirectory::Cols::_updated_at = "\"updated_at\"";
const std::string UssdDirectory::primaryKeyName = "id";
const bool UssdDirectory::hasPrimaryKey = true;
const std::string UssdDirectory::tableName = "\"ussd_directory\"";

const std::vector<typename UssdDirectory::MetaData> UssdDirectory::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"trade_name","std::string","character varying",150,0,0,0},
{"ussd_code","std::string","character varying",20,0,0,1},
{"business_name","std::string","character varying",100,0,0,0},
{"description","std::string","character varying",250,0,0,0},
{"country_code","std::string","character varying",50,0,0,0},
{"category","std::string","character varying",100,0,0,0},
{"keywords","std::string","character varying",200,0,0,0},
{"is_dedicated","bool","boolean",1,0,0,0},
{"is_wssd_linked","bool","boolean",1,0,0,0},
{"rating","int32_t","integer",4,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"updated_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &UssdDirectory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UssdDirectory::UssdDirectory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["trade_name"].isNull())
        {
            tradeName_=std::make_shared<std::string>(r["trade_name"].as<std::string>());
        }
        if(!r["ussd_code"].isNull())
        {
            ussdCode_=std::make_shared<std::string>(r["ussd_code"].as<std::string>());
        }
        if(!r["business_name"].isNull())
        {
            businessName_=std::make_shared<std::string>(r["business_name"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["country_code"].isNull())
        {
            countryCode_=std::make_shared<std::string>(r["country_code"].as<std::string>());
        }
        if(!r["category"].isNull())
        {
            category_=std::make_shared<std::string>(r["category"].as<std::string>());
        }
        if(!r["keywords"].isNull())
        {
            keywords_=std::make_shared<std::string>(r["keywords"].as<std::string>());
        }
        if(!r["is_dedicated"].isNull())
        {
            isDedicated_=std::make_shared<bool>(r["is_dedicated"].as<bool>());
        }
        if(!r["is_wssd_linked"].isNull())
        {
            isWssdLinked_=std::make_shared<bool>(r["is_wssd_linked"].as<bool>());
        }
        if(!r["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>(r["rating"].as<int32_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            tradeName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            ussdCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            businessName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            countryCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            category_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            keywords_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            isDedicated_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            isWssdLinked_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            rating_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UssdDirectory::UssdDirectory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tradeName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            countryCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            category_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            keywords_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            isDedicated_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            isWssdLinked_=std::make_shared<bool>(pJson[pMasqueradingVector[9]].asBool());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UssdDirectory::UssdDirectory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("trade_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["trade_name"].isNull())
        {
            tradeName_=std::make_shared<std::string>(pJson["trade_name"].asString());
        }
    }
    if(pJson.isMember("ussd_code"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["ussd_code"].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson["ussd_code"].asString());
        }
    }
    if(pJson.isMember("business_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["business_name"].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson["business_name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("country_code"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["country_code"].isNull())
        {
            countryCode_=std::make_shared<std::string>(pJson["country_code"].asString());
        }
    }
    if(pJson.isMember("category"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["category"].isNull())
        {
            category_=std::make_shared<std::string>(pJson["category"].asString());
        }
    }
    if(pJson.isMember("keywords"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["keywords"].isNull())
        {
            keywords_=std::make_shared<std::string>(pJson["keywords"].asString());
        }
    }
    if(pJson.isMember("is_dedicated"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["is_dedicated"].isNull())
        {
            isDedicated_=std::make_shared<bool>(pJson["is_dedicated"].asBool());
        }
    }
    if(pJson.isMember("is_wssd_linked"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["is_wssd_linked"].isNull())
        {
            isWssdLinked_=std::make_shared<bool>(pJson["is_wssd_linked"].asBool());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson["rating"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UssdDirectory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tradeName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            countryCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            category_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            keywords_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            isDedicated_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            isWssdLinked_=std::make_shared<bool>(pJson[pMasqueradingVector[9]].asBool());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UssdDirectory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("trade_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["trade_name"].isNull())
        {
            tradeName_=std::make_shared<std::string>(pJson["trade_name"].asString());
        }
    }
    if(pJson.isMember("ussd_code"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["ussd_code"].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson["ussd_code"].asString());
        }
    }
    if(pJson.isMember("business_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["business_name"].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson["business_name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("country_code"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["country_code"].isNull())
        {
            countryCode_=std::make_shared<std::string>(pJson["country_code"].asString());
        }
    }
    if(pJson.isMember("category"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["category"].isNull())
        {
            category_=std::make_shared<std::string>(pJson["category"].asString());
        }
    }
    if(pJson.isMember("keywords"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["keywords"].isNull())
        {
            keywords_=std::make_shared<std::string>(pJson["keywords"].asString());
        }
    }
    if(pJson.isMember("is_dedicated"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["is_dedicated"].isNull())
        {
            isDedicated_=std::make_shared<bool>(pJson["is_dedicated"].asBool());
        }
    }
    if(pJson.isMember("is_wssd_linked"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["is_wssd_linked"].isNull())
        {
            isWssdLinked_=std::make_shared<bool>(pJson["is_wssd_linked"].asBool());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<int32_t>((int32_t)pJson["rating"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &UssdDirectory::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getId() const noexcept
{
    return id_;
}
void UssdDirectory::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void UssdDirectory::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename UssdDirectory::PrimaryKeyType & UssdDirectory::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &UssdDirectory::getValueOfTradeName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tradeName_)
        return *tradeName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getTradeName() const noexcept
{
    return tradeName_;
}
void UssdDirectory::setTradeName(const std::string &pTradeName) noexcept
{
    tradeName_ = std::make_shared<std::string>(pTradeName);
    dirtyFlag_[1] = true;
}
void UssdDirectory::setTradeName(std::string &&pTradeName) noexcept
{
    tradeName_ = std::make_shared<std::string>(std::move(pTradeName));
    dirtyFlag_[1] = true;
}
void UssdDirectory::setTradeNameToNull() noexcept
{
    tradeName_.reset();
    dirtyFlag_[1] = true;
}

const std::string &UssdDirectory::getValueOfUssdCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ussdCode_)
        return *ussdCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getUssdCode() const noexcept
{
    return ussdCode_;
}
void UssdDirectory::setUssdCode(const std::string &pUssdCode) noexcept
{
    ussdCode_ = std::make_shared<std::string>(pUssdCode);
    dirtyFlag_[2] = true;
}
void UssdDirectory::setUssdCode(std::string &&pUssdCode) noexcept
{
    ussdCode_ = std::make_shared<std::string>(std::move(pUssdCode));
    dirtyFlag_[2] = true;
}

const std::string &UssdDirectory::getValueOfBusinessName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(businessName_)
        return *businessName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getBusinessName() const noexcept
{
    return businessName_;
}
void UssdDirectory::setBusinessName(const std::string &pBusinessName) noexcept
{
    businessName_ = std::make_shared<std::string>(pBusinessName);
    dirtyFlag_[3] = true;
}
void UssdDirectory::setBusinessName(std::string &&pBusinessName) noexcept
{
    businessName_ = std::make_shared<std::string>(std::move(pBusinessName));
    dirtyFlag_[3] = true;
}
void UssdDirectory::setBusinessNameToNull() noexcept
{
    businessName_.reset();
    dirtyFlag_[3] = true;
}

const std::string &UssdDirectory::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getDescription() const noexcept
{
    return description_;
}
void UssdDirectory::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[4] = true;
}
void UssdDirectory::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[4] = true;
}
void UssdDirectory::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[4] = true;
}

const std::string &UssdDirectory::getValueOfCountryCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(countryCode_)
        return *countryCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getCountryCode() const noexcept
{
    return countryCode_;
}
void UssdDirectory::setCountryCode(const std::string &pCountryCode) noexcept
{
    countryCode_ = std::make_shared<std::string>(pCountryCode);
    dirtyFlag_[5] = true;
}
void UssdDirectory::setCountryCode(std::string &&pCountryCode) noexcept
{
    countryCode_ = std::make_shared<std::string>(std::move(pCountryCode));
    dirtyFlag_[5] = true;
}
void UssdDirectory::setCountryCodeToNull() noexcept
{
    countryCode_.reset();
    dirtyFlag_[5] = true;
}

const std::string &UssdDirectory::getValueOfCategory() const noexcept
{
    static const std::string defaultValue = std::string();
    if(category_)
        return *category_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getCategory() const noexcept
{
    return category_;
}
void UssdDirectory::setCategory(const std::string &pCategory) noexcept
{
    category_ = std::make_shared<std::string>(pCategory);
    dirtyFlag_[6] = true;
}
void UssdDirectory::setCategory(std::string &&pCategory) noexcept
{
    category_ = std::make_shared<std::string>(std::move(pCategory));
    dirtyFlag_[6] = true;
}
void UssdDirectory::setCategoryToNull() noexcept
{
    category_.reset();
    dirtyFlag_[6] = true;
}

const std::string &UssdDirectory::getValueOfKeywords() const noexcept
{
    static const std::string defaultValue = std::string();
    if(keywords_)
        return *keywords_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UssdDirectory::getKeywords() const noexcept
{
    return keywords_;
}
void UssdDirectory::setKeywords(const std::string &pKeywords) noexcept
{
    keywords_ = std::make_shared<std::string>(pKeywords);
    dirtyFlag_[7] = true;
}
void UssdDirectory::setKeywords(std::string &&pKeywords) noexcept
{
    keywords_ = std::make_shared<std::string>(std::move(pKeywords));
    dirtyFlag_[7] = true;
}
void UssdDirectory::setKeywordsToNull() noexcept
{
    keywords_.reset();
    dirtyFlag_[7] = true;
}

const bool &UssdDirectory::getValueOfIsDedicated() const noexcept
{
    static const bool defaultValue = bool();
    if(isDedicated_)
        return *isDedicated_;
    return defaultValue;
}
const std::shared_ptr<bool> &UssdDirectory::getIsDedicated() const noexcept
{
    return isDedicated_;
}
void UssdDirectory::setIsDedicated(const bool &pIsDedicated) noexcept
{
    isDedicated_ = std::make_shared<bool>(pIsDedicated);
    dirtyFlag_[8] = true;
}
void UssdDirectory::setIsDedicatedToNull() noexcept
{
    isDedicated_.reset();
    dirtyFlag_[8] = true;
}

const bool &UssdDirectory::getValueOfIsWssdLinked() const noexcept
{
    static const bool defaultValue = bool();
    if(isWssdLinked_)
        return *isWssdLinked_;
    return defaultValue;
}
const std::shared_ptr<bool> &UssdDirectory::getIsWssdLinked() const noexcept
{
    return isWssdLinked_;
}
void UssdDirectory::setIsWssdLinked(const bool &pIsWssdLinked) noexcept
{
    isWssdLinked_ = std::make_shared<bool>(pIsWssdLinked);
    dirtyFlag_[9] = true;
}
void UssdDirectory::setIsWssdLinkedToNull() noexcept
{
    isWssdLinked_.reset();
    dirtyFlag_[9] = true;
}

const int32_t &UssdDirectory::getValueOfRating() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(rating_)
        return *rating_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UssdDirectory::getRating() const noexcept
{
    return rating_;
}
void UssdDirectory::setRating(const int32_t &pRating) noexcept
{
    rating_ = std::make_shared<int32_t>(pRating);
    dirtyFlag_[10] = true;
}
void UssdDirectory::setRatingToNull() noexcept
{
    rating_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &UssdDirectory::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UssdDirectory::getCreatedAt() const noexcept
{
    return createdAt_;
}
void UssdDirectory::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[11] = true;
}
void UssdDirectory::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &UssdDirectory::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UssdDirectory::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void UssdDirectory::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[12] = true;
}
void UssdDirectory::setUpdatedAtToNull() noexcept
{
    updatedAt_.reset();
    dirtyFlag_[12] = true;
}

void UssdDirectory::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UssdDirectory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "trade_name",
        "ussd_code",
        "business_name",
        "description",
        "country_code",
        "category",
        "keywords",
        "is_dedicated",
        "is_wssd_linked",
        "rating",
        "created_at",
        "updated_at"
    };
    return inCols;
}

void UssdDirectory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTradeName())
        {
            binder << getValueOfTradeName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUssdCode())
        {
            binder << getValueOfUssdCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getBusinessName())
        {
            binder << getValueOfBusinessName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCountryCode())
        {
            binder << getValueOfCountryCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCategory())
        {
            binder << getValueOfCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getKeywords())
        {
            binder << getValueOfKeywords();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIsDedicated())
        {
            binder << getValueOfIsDedicated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getIsWssdLinked())
        {
            binder << getValueOfIsWssdLinked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UssdDirectory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void UssdDirectory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTradeName())
        {
            binder << getValueOfTradeName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUssdCode())
        {
            binder << getValueOfUssdCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getBusinessName())
        {
            binder << getValueOfBusinessName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCountryCode())
        {
            binder << getValueOfCountryCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCategory())
        {
            binder << getValueOfCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getKeywords())
        {
            binder << getValueOfKeywords();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIsDedicated())
        {
            binder << getValueOfIsDedicated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getIsWssdLinked())
        {
            binder << getValueOfIsWssdLinked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UssdDirectory::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTradeName())
    {
        ret["trade_name"]=getValueOfTradeName();
    }
    else
    {
        ret["trade_name"]=Json::Value();
    }
    if(getUssdCode())
    {
        ret["ussd_code"]=getValueOfUssdCode();
    }
    else
    {
        ret["ussd_code"]=Json::Value();
    }
    if(getBusinessName())
    {
        ret["business_name"]=getValueOfBusinessName();
    }
    else
    {
        ret["business_name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getCountryCode())
    {
        ret["country_code"]=getValueOfCountryCode();
    }
    else
    {
        ret["country_code"]=Json::Value();
    }
    if(getCategory())
    {
        ret["category"]=getValueOfCategory();
    }
    else
    {
        ret["category"]=Json::Value();
    }
    if(getKeywords())
    {
        ret["keywords"]=getValueOfKeywords();
    }
    else
    {
        ret["keywords"]=Json::Value();
    }
    if(getIsDedicated())
    {
        ret["is_dedicated"]=getValueOfIsDedicated();
    }
    else
    {
        ret["is_dedicated"]=Json::Value();
    }
    if(getIsWssdLinked())
    {
        ret["is_wssd_linked"]=getValueOfIsWssdLinked();
    }
    else
    {
        ret["is_wssd_linked"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string UssdDirectory::toString() const
{
    return toJson().toStyledString();
}

Json::Value UssdDirectory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTradeName())
            {
                ret[pMasqueradingVector[1]]=getValueOfTradeName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUssdCode())
            {
                ret[pMasqueradingVector[2]]=getValueOfUssdCode();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getBusinessName())
            {
                ret[pMasqueradingVector[3]]=getValueOfBusinessName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[4]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCountryCode())
            {
                ret[pMasqueradingVector[5]]=getValueOfCountryCode();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCategory())
            {
                ret[pMasqueradingVector[6]]=getValueOfCategory();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getKeywords())
            {
                ret[pMasqueradingVector[7]]=getValueOfKeywords();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getIsDedicated())
            {
                ret[pMasqueradingVector[8]]=getValueOfIsDedicated();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getIsWssdLinked())
            {
                ret[pMasqueradingVector[9]]=getValueOfIsWssdLinked();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getRating())
            {
                ret[pMasqueradingVector[10]]=getValueOfRating();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[11]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[12]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTradeName())
    {
        ret["trade_name"]=getValueOfTradeName();
    }
    else
    {
        ret["trade_name"]=Json::Value();
    }
    if(getUssdCode())
    {
        ret["ussd_code"]=getValueOfUssdCode();
    }
    else
    {
        ret["ussd_code"]=Json::Value();
    }
    if(getBusinessName())
    {
        ret["business_name"]=getValueOfBusinessName();
    }
    else
    {
        ret["business_name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getCountryCode())
    {
        ret["country_code"]=getValueOfCountryCode();
    }
    else
    {
        ret["country_code"]=Json::Value();
    }
    if(getCategory())
    {
        ret["category"]=getValueOfCategory();
    }
    else
    {
        ret["category"]=Json::Value();
    }
    if(getKeywords())
    {
        ret["keywords"]=getValueOfKeywords();
    }
    else
    {
        ret["keywords"]=Json::Value();
    }
    if(getIsDedicated())
    {
        ret["is_dedicated"]=getValueOfIsDedicated();
    }
    else
    {
        ret["is_dedicated"]=Json::Value();
    }
    if(getIsWssdLinked())
    {
        ret["is_wssd_linked"]=getValueOfIsWssdLinked();
    }
    else
    {
        ret["is_wssd_linked"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool UssdDirectory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("trade_name"))
    {
        if(!validJsonOfField(1, "trade_name", pJson["trade_name"], err, true))
            return false;
    }
    if(pJson.isMember("ussd_code"))
    {
        if(!validJsonOfField(2, "ussd_code", pJson["ussd_code"], err, true))
            return false;
    }
    else
    {
        err="The ussd_code column cannot be null";
        return false;
    }
    if(pJson.isMember("business_name"))
    {
        if(!validJsonOfField(3, "business_name", pJson["business_name"], err, true))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("country_code"))
    {
        if(!validJsonOfField(5, "country_code", pJson["country_code"], err, true))
            return false;
    }
    if(pJson.isMember("category"))
    {
        if(!validJsonOfField(6, "category", pJson["category"], err, true))
            return false;
    }
    if(pJson.isMember("keywords"))
    {
        if(!validJsonOfField(7, "keywords", pJson["keywords"], err, true))
            return false;
    }
    if(pJson.isMember("is_dedicated"))
    {
        if(!validJsonOfField(8, "is_dedicated", pJson["is_dedicated"], err, true))
            return false;
    }
    if(pJson.isMember("is_wssd_linked"))
    {
        if(!validJsonOfField(9, "is_wssd_linked", pJson["is_wssd_linked"], err, true))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(10, "rating", pJson["rating"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(12, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool UssdDirectory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UssdDirectory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("trade_name"))
    {
        if(!validJsonOfField(1, "trade_name", pJson["trade_name"], err, false))
            return false;
    }
    if(pJson.isMember("ussd_code"))
    {
        if(!validJsonOfField(2, "ussd_code", pJson["ussd_code"], err, false))
            return false;
    }
    if(pJson.isMember("business_name"))
    {
        if(!validJsonOfField(3, "business_name", pJson["business_name"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("country_code"))
    {
        if(!validJsonOfField(5, "country_code", pJson["country_code"], err, false))
            return false;
    }
    if(pJson.isMember("category"))
    {
        if(!validJsonOfField(6, "category", pJson["category"], err, false))
            return false;
    }
    if(pJson.isMember("keywords"))
    {
        if(!validJsonOfField(7, "keywords", pJson["keywords"], err, false))
            return false;
    }
    if(pJson.isMember("is_dedicated"))
    {
        if(!validJsonOfField(8, "is_dedicated", pJson["is_dedicated"], err, false))
            return false;
    }
    if(pJson.isMember("is_wssd_linked"))
    {
        if(!validJsonOfField(9, "is_wssd_linked", pJson["is_wssd_linked"], err, false))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(10, "rating", pJson["rating"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(11, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(12, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool UssdDirectory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UssdDirectory::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 150)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 150)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 250)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 250)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 200)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 200)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
