/**
 *
 *  UssdDirectory.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace WssdApi
{

class UssdDirectory
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _trade_name;
        static const std::string _ussd_code;
        static const std::string _business_name;
        static const std::string _description;
        static const std::string _country_code;
        static const std::string _category;
        static const std::string _keywords;
        static const std::string _is_dedicated;
        static const std::string _is_wssd_linked;
        static const std::string _rating;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit UssdDirectory(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit UssdDirectory(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    UssdDirectory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    UssdDirectory() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column trade_name  */
    ///Get the value of the column trade_name, returns the default value if the column is null
    const std::string &getValueOfTradeName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTradeName() const noexcept;
    ///Set the value of the column trade_name
    void setTradeName(const std::string &pTradeName) noexcept;
    void setTradeName(std::string &&pTradeName) noexcept;
    void setTradeNameToNull() noexcept;

    /**  For column ussd_code  */
    ///Get the value of the column ussd_code, returns the default value if the column is null
    const std::string &getValueOfUssdCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUssdCode() const noexcept;
    ///Set the value of the column ussd_code
    void setUssdCode(const std::string &pUssdCode) noexcept;
    void setUssdCode(std::string &&pUssdCode) noexcept;

    /**  For column business_name  */
    ///Get the value of the column business_name, returns the default value if the column is null
    const std::string &getValueOfBusinessName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBusinessName() const noexcept;
    ///Set the value of the column business_name
    void setBusinessName(const std::string &pBusinessName) noexcept;
    void setBusinessName(std::string &&pBusinessName) noexcept;
    void setBusinessNameToNull() noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column country_code  */
    ///Get the value of the column country_code, returns the default value if the column is null
    const std::string &getValueOfCountryCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCountryCode() const noexcept;
    ///Set the value of the column country_code
    void setCountryCode(const std::string &pCountryCode) noexcept;
    void setCountryCode(std::string &&pCountryCode) noexcept;
    void setCountryCodeToNull() noexcept;

    /**  For column category  */
    ///Get the value of the column category, returns the default value if the column is null
    const std::string &getValueOfCategory() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCategory() const noexcept;
    ///Set the value of the column category
    void setCategory(const std::string &pCategory) noexcept;
    void setCategory(std::string &&pCategory) noexcept;
    void setCategoryToNull() noexcept;

    /**  For column keywords  */
    ///Get the value of the column keywords, returns the default value if the column is null
    const std::string &getValueOfKeywords() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getKeywords() const noexcept;
    ///Set the value of the column keywords
    void setKeywords(const std::string &pKeywords) noexcept;
    void setKeywords(std::string &&pKeywords) noexcept;
    void setKeywordsToNull() noexcept;

    /**  For column is_dedicated  */
    ///Get the value of the column is_dedicated, returns the default value if the column is null
    const bool &getValueOfIsDedicated() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsDedicated() const noexcept;
    ///Set the value of the column is_dedicated
    void setIsDedicated(const bool &pIsDedicated) noexcept;
    void setIsDedicatedToNull() noexcept;

    /**  For column is_wssd_linked  */
    ///Get the value of the column is_wssd_linked, returns the default value if the column is null
    const bool &getValueOfIsWssdLinked() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsWssdLinked() const noexcept;
    ///Set the value of the column is_wssd_linked
    void setIsWssdLinked(const bool &pIsWssdLinked) noexcept;
    void setIsWssdLinkedToNull() noexcept;

    /**  For column rating  */
    ///Get the value of the column rating, returns the default value if the column is null
    const int32_t &getValueOfRating() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRating() const noexcept;
    ///Set the value of the column rating
    void setRating(const int32_t &pRating) noexcept;
    void setRatingToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<UssdDirectory>;
    friend drogon::orm::BaseBuilder<UssdDirectory, true, true>;
    friend drogon::orm::BaseBuilder<UssdDirectory, true, false>;
    friend drogon::orm::BaseBuilder<UssdDirectory, false, true>;
    friend drogon::orm::BaseBuilder<UssdDirectory, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<UssdDirectory>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> tradeName_;
    std::shared_ptr<std::string> ussdCode_;
    std::shared_ptr<std::string> businessName_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> countryCode_;
    std::shared_ptr<std::string> category_;
    std::shared_ptr<std::string> keywords_;
    std::shared_ptr<bool> isDedicated_;
    std::shared_ptr<bool> isWssdLinked_;
    std::shared_ptr<int32_t> rating_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "trade_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "ussd_code,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "business_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "country_code,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "category,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "keywords,";
            ++parametersCount;
        }
        sql += "is_dedicated,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        sql += "is_wssd_linked,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        if(dirtyFlag_[10])
        {
            sql += "rating,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[11])
        {
            needSelection=true;
        }
        if(dirtyFlag_[12])
        {
            sql += "updated_at,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace WssdApi
} // namespace drogon_model
