/**
 *
 *  WssdSubscriptions.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace WssdApi
{

class WssdSubscriptions
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _business_id;
        static const std::string _business_name;
        static const std::string _service_id;
        static const std::string _subscription_plan_id;
        static const std::string _service_name;
        static const std::string _service_provider;
        static const std::string _fee;
        static const std::string _billing_cycle;
        static const std::string _session_rate;
        static const std::string _session_account_balance;
        static const std::string _start_date;
        static const std::string _end_date;
        static const std::string _last_activity;
        static const std::string _is_active;
        static const std::string _is_ported;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit WssdSubscriptions(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit WssdSubscriptions(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    WssdSubscriptions(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    WssdSubscriptions() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column business_id  */
    ///Get the value of the column business_id, returns the default value if the column is null
    const std::string &getValueOfBusinessId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBusinessId() const noexcept;
    ///Set the value of the column business_id
    void setBusinessId(const std::string &pBusinessId) noexcept;
    void setBusinessId(std::string &&pBusinessId) noexcept;

    /**  For column business_name  */
    ///Get the value of the column business_name, returns the default value if the column is null
    const std::string &getValueOfBusinessName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBusinessName() const noexcept;
    ///Set the value of the column business_name
    void setBusinessName(const std::string &pBusinessName) noexcept;
    void setBusinessName(std::string &&pBusinessName) noexcept;
    void setBusinessNameToNull() noexcept;

    /**  For column service_id  */
    ///Get the value of the column service_id, returns the default value if the column is null
    const std::string &getValueOfServiceId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getServiceId() const noexcept;
    ///Set the value of the column service_id
    void setServiceId(const std::string &pServiceId) noexcept;
    void setServiceId(std::string &&pServiceId) noexcept;
    void setServiceIdToNull() noexcept;

    /**  For column subscription_plan_id  */
    ///Get the value of the column subscription_plan_id, returns the default value if the column is null
    const std::string &getValueOfSubscriptionPlanId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSubscriptionPlanId() const noexcept;
    ///Set the value of the column subscription_plan_id
    void setSubscriptionPlanId(const std::string &pSubscriptionPlanId) noexcept;
    void setSubscriptionPlanId(std::string &&pSubscriptionPlanId) noexcept;
    void setSubscriptionPlanIdToNull() noexcept;

    /**  For column service_name  */
    ///Get the value of the column service_name, returns the default value if the column is null
    const std::string &getValueOfServiceName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getServiceName() const noexcept;
    ///Set the value of the column service_name
    void setServiceName(const std::string &pServiceName) noexcept;
    void setServiceName(std::string &&pServiceName) noexcept;
    void setServiceNameToNull() noexcept;

    /**  For column service_provider  */
    ///Get the value of the column service_provider, returns the default value if the column is null
    const std::string &getValueOfServiceProvider() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getServiceProvider() const noexcept;
    ///Set the value of the column service_provider
    void setServiceProvider(const std::string &pServiceProvider) noexcept;
    void setServiceProvider(std::string &&pServiceProvider) noexcept;
    void setServiceProviderToNull() noexcept;

    /**  For column fee  */
    ///Get the value of the column fee, returns the default value if the column is null
    const std::string &getValueOfFee() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFee() const noexcept;
    ///Set the value of the column fee
    void setFee(const std::string &pFee) noexcept;
    void setFee(std::string &&pFee) noexcept;

    /**  For column billing_cycle  */
    ///Get the value of the column billing_cycle, returns the default value if the column is null
    const std::string &getValueOfBillingCycle() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBillingCycle() const noexcept;
    ///Set the value of the column billing_cycle
    void setBillingCycle(const std::string &pBillingCycle) noexcept;
    void setBillingCycle(std::string &&pBillingCycle) noexcept;
    void setBillingCycleToNull() noexcept;

    /**  For column session_rate  */
    ///Get the value of the column session_rate, returns the default value if the column is null
    const std::string &getValueOfSessionRate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSessionRate() const noexcept;
    ///Set the value of the column session_rate
    void setSessionRate(const std::string &pSessionRate) noexcept;
    void setSessionRate(std::string &&pSessionRate) noexcept;

    /**  For column session_account_balance  */
    ///Get the value of the column session_account_balance, returns the default value if the column is null
    const std::string &getValueOfSessionAccountBalance() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSessionAccountBalance() const noexcept;
    ///Set the value of the column session_account_balance
    void setSessionAccountBalance(const std::string &pSessionAccountBalance) noexcept;
    void setSessionAccountBalance(std::string &&pSessionAccountBalance) noexcept;

    /**  For column start_date  */
    ///Get the value of the column start_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfStartDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getStartDate() const noexcept;
    ///Set the value of the column start_date
    void setStartDate(const ::trantor::Date &pStartDate) noexcept;
    void setStartDateToNull() noexcept;

    /**  For column end_date  */
    ///Get the value of the column end_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfEndDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEndDate() const noexcept;
    ///Set the value of the column end_date
    void setEndDate(const ::trantor::Date &pEndDate) noexcept;
    void setEndDateToNull() noexcept;

    /**  For column last_activity  */
    ///Get the value of the column last_activity, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastActivity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastActivity() const noexcept;
    ///Set the value of the column last_activity
    void setLastActivity(const ::trantor::Date &pLastActivity) noexcept;
    void setLastActivityToNull() noexcept;

    /**  For column is_active  */
    ///Get the value of the column is_active, returns the default value if the column is null
    const bool &getValueOfIsActive() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsActive() const noexcept;
    ///Set the value of the column is_active
    void setIsActive(const bool &pIsActive) noexcept;
    void setIsActiveToNull() noexcept;

    /**  For column is_ported  */
    ///Get the value of the column is_ported, returns the default value if the column is null
    const bool &getValueOfIsPorted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsPorted() const noexcept;
    ///Set the value of the column is_ported
    void setIsPorted(const bool &pIsPorted) noexcept;
    void setIsPortedToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 18;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<WssdSubscriptions>;
    friend drogon::orm::BaseBuilder<WssdSubscriptions, true, true>;
    friend drogon::orm::BaseBuilder<WssdSubscriptions, true, false>;
    friend drogon::orm::BaseBuilder<WssdSubscriptions, false, true>;
    friend drogon::orm::BaseBuilder<WssdSubscriptions, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<WssdSubscriptions>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> businessId_;
    std::shared_ptr<std::string> businessName_;
    std::shared_ptr<std::string> serviceId_;
    std::shared_ptr<std::string> subscriptionPlanId_;
    std::shared_ptr<std::string> serviceName_;
    std::shared_ptr<std::string> serviceProvider_;
    std::shared_ptr<std::string> fee_;
    std::shared_ptr<std::string> billingCycle_;
    std::shared_ptr<std::string> sessionRate_;
    std::shared_ptr<std::string> sessionAccountBalance_;
    std::shared_ptr<::trantor::Date> startDate_;
    std::shared_ptr<::trantor::Date> endDate_;
    std::shared_ptr<::trantor::Date> lastActivity_;
    std::shared_ptr<bool> isActive_;
    std::shared_ptr<bool> isPorted_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[18]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "business_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "business_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "service_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "subscription_plan_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "service_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "service_provider,";
            ++parametersCount;
        }
        sql += "fee,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(dirtyFlag_[8])
        {
            sql += "billing_cycle,";
            ++parametersCount;
        }
        sql += "session_rate,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        sql += "session_account_balance,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        if(dirtyFlag_[11])
        {
            sql += "start_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "end_date,";
            ++parametersCount;
        }
        sql += "last_activity,";
        ++parametersCount;
        if(!dirtyFlag_[13])
        {
            needSelection=true;
        }
        sql += "is_active,";
        ++parametersCount;
        if(!dirtyFlag_[14])
        {
            needSelection=true;
        }
        sql += "is_ported,";
        ++parametersCount;
        if(!dirtyFlag_[15])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[16])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[17])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[15])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[16])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[17])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace WssdApi
} // namespace drogon_model
