/**
 *
 *  WssdRegistry.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "WssdRegistry.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::WssdApi;

const std::string WssdRegistry::Cols::_id = "\"id\"";
const std::string WssdRegistry::Cols::_wssd_short_name = "\"wssd_short_name\"";
const std::string WssdRegistry::Cols::_ussd_code = "\"ussd_code\"";
const std::string WssdRegistry::Cols::_display_title = "\"display_title\"";
const std::string WssdRegistry::Cols::_description = "\"description\"";
const std::string WssdRegistry::Cols::_activated_on = "\"activated_on\"";
const std::string WssdRegistry::Cols::_logo_url = "\"logo_url\"";
const std::string WssdRegistry::Cols::_tenant_id = "\"tenant_id\"";
const std::string WssdRegistry::Cols::_service_type = "\"service_type\"";
const std::string WssdRegistry::Cols::_rank = "\"rank\"";
const std::string WssdRegistry::Cols::_merchant_identifier = "\"merchant_identifier\"";
const std::string WssdRegistry::Cols::_category = "\"category\"";
const std::string WssdRegistry::Cols::_business_name = "\"business_name\"";
const std::string WssdRegistry::Cols::_executable = "\"executable\"";
const std::string WssdRegistry::Cols::_created_at = "\"created_at\"";
const std::string WssdRegistry::Cols::_updated_at = "\"updated_at\"";
const std::string WssdRegistry::primaryKeyName = "id";
const bool WssdRegistry::hasPrimaryKey = true;
const std::string WssdRegistry::tableName = "\"wssd_registry\"";

const std::vector<typename WssdRegistry::MetaData> WssdRegistry::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"wssd_short_name","std::string","character varying",100,0,0,0},
{"ussd_code","std::string","character varying",25,0,0,0},
{"display_title","std::string","character varying",100,0,0,0},
{"description","std::string","character varying",250,0,0,0},
{"activated_on","::trantor::Date","timestamp with time zone",0,0,0,0},
{"logo_url","std::string","character varying",300,0,0,0},
{"tenant_id","int32_t","integer",4,0,0,1},
{"service_type","int32_t","integer",4,0,0,1},
{"rank","int32_t","integer",4,0,0,1},
{"merchant_identifier","std::string","character varying",50,0,0,0},
{"category","std::string","character varying",80,0,0,0},
{"business_name","std::string","character varying",60,0,0,0},
{"executable","std::string","jsonb",0,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"updated_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &WssdRegistry::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
WssdRegistry::WssdRegistry(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["wssd_short_name"].isNull())
        {
            wssdShortName_=std::make_shared<std::string>(r["wssd_short_name"].as<std::string>());
        }
        if(!r["ussd_code"].isNull())
        {
            ussdCode_=std::make_shared<std::string>(r["ussd_code"].as<std::string>());
        }
        if(!r["display_title"].isNull())
        {
            displayTitle_=std::make_shared<std::string>(r["display_title"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["activated_on"].isNull())
        {
            auto timeStr = r["activated_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                activatedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["logo_url"].isNull())
        {
            logoUrl_=std::make_shared<std::string>(r["logo_url"].as<std::string>());
        }
        if(!r["tenant_id"].isNull())
        {
            tenantId_=std::make_shared<int32_t>(r["tenant_id"].as<int32_t>());
        }
        if(!r["service_type"].isNull())
        {
            serviceType_=std::make_shared<int32_t>(r["service_type"].as<int32_t>());
        }
        if(!r["rank"].isNull())
        {
            rank_=std::make_shared<int32_t>(r["rank"].as<int32_t>());
        }
        if(!r["merchant_identifier"].isNull())
        {
            merchantIdentifier_=std::make_shared<std::string>(r["merchant_identifier"].as<std::string>());
        }
        if(!r["category"].isNull())
        {
            category_=std::make_shared<std::string>(r["category"].as<std::string>());
        }
        if(!r["business_name"].isNull())
        {
            businessName_=std::make_shared<std::string>(r["business_name"].as<std::string>());
        }
        if(!r["executable"].isNull())
        {
            executable_=std::make_shared<std::string>(r["executable"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 16 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            wssdShortName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            ussdCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            displayTitle_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                activatedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            logoUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            tenantId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            serviceType_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            rank_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            merchantIdentifier_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            category_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            businessName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            executable_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 15;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

WssdRegistry::WssdRegistry(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 16)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            wssdShortName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            displayTitle_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                activatedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            tenantId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            serviceType_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            rank_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            merchantIdentifier_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            category_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            executable_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[14]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

WssdRegistry::WssdRegistry(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("wssd_short_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["wssd_short_name"].isNull())
        {
            wssdShortName_=std::make_shared<std::string>(pJson["wssd_short_name"].asString());
        }
    }
    if(pJson.isMember("ussd_code"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["ussd_code"].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson["ussd_code"].asString());
        }
    }
    if(pJson.isMember("display_title"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["display_title"].isNull())
        {
            displayTitle_=std::make_shared<std::string>(pJson["display_title"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("activated_on"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["activated_on"].isNull())
        {
            auto timeStr = pJson["activated_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                activatedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("logo_url"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["logo_url"].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson["logo_url"].asString());
        }
    }
    if(pJson.isMember("tenant_id"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["tenant_id"].isNull())
        {
            tenantId_=std::make_shared<int32_t>((int32_t)pJson["tenant_id"].asInt64());
        }
    }
    if(pJson.isMember("service_type"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["service_type"].isNull())
        {
            serviceType_=std::make_shared<int32_t>((int32_t)pJson["service_type"].asInt64());
        }
    }
    if(pJson.isMember("rank"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["rank"].isNull())
        {
            rank_=std::make_shared<int32_t>((int32_t)pJson["rank"].asInt64());
        }
    }
    if(pJson.isMember("merchant_identifier"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["merchant_identifier"].isNull())
        {
            merchantIdentifier_=std::make_shared<std::string>(pJson["merchant_identifier"].asString());
        }
    }
    if(pJson.isMember("category"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["category"].isNull())
        {
            category_=std::make_shared<std::string>(pJson["category"].asString());
        }
    }
    if(pJson.isMember("business_name"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["business_name"].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson["business_name"].asString());
        }
    }
    if(pJson.isMember("executable"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["executable"].isNull())
        {
            executable_=std::make_shared<std::string>(pJson["executable"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[15]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WssdRegistry::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 16)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            wssdShortName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            displayTitle_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                activatedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            tenantId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            serviceType_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            rank_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            merchantIdentifier_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            category_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            executable_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[14]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WssdRegistry::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("wssd_short_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["wssd_short_name"].isNull())
        {
            wssdShortName_=std::make_shared<std::string>(pJson["wssd_short_name"].asString());
        }
    }
    if(pJson.isMember("ussd_code"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["ussd_code"].isNull())
        {
            ussdCode_=std::make_shared<std::string>(pJson["ussd_code"].asString());
        }
    }
    if(pJson.isMember("display_title"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["display_title"].isNull())
        {
            displayTitle_=std::make_shared<std::string>(pJson["display_title"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("activated_on"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["activated_on"].isNull())
        {
            auto timeStr = pJson["activated_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                activatedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("logo_url"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["logo_url"].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson["logo_url"].asString());
        }
    }
    if(pJson.isMember("tenant_id"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["tenant_id"].isNull())
        {
            tenantId_=std::make_shared<int32_t>((int32_t)pJson["tenant_id"].asInt64());
        }
    }
    if(pJson.isMember("service_type"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["service_type"].isNull())
        {
            serviceType_=std::make_shared<int32_t>((int32_t)pJson["service_type"].asInt64());
        }
    }
    if(pJson.isMember("rank"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["rank"].isNull())
        {
            rank_=std::make_shared<int32_t>((int32_t)pJson["rank"].asInt64());
        }
    }
    if(pJson.isMember("merchant_identifier"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["merchant_identifier"].isNull())
        {
            merchantIdentifier_=std::make_shared<std::string>(pJson["merchant_identifier"].asString());
        }
    }
    if(pJson.isMember("category"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["category"].isNull())
        {
            category_=std::make_shared<std::string>(pJson["category"].asString());
        }
    }
    if(pJson.isMember("business_name"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["business_name"].isNull())
        {
            businessName_=std::make_shared<std::string>(pJson["business_name"].asString());
        }
    }
    if(pJson.isMember("executable"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["executable"].isNull())
        {
            executable_=std::make_shared<std::string>(pJson["executable"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[15] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &WssdRegistry::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getId() const noexcept
{
    return id_;
}
void WssdRegistry::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void WssdRegistry::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename WssdRegistry::PrimaryKeyType & WssdRegistry::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &WssdRegistry::getValueOfWssdShortName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(wssdShortName_)
        return *wssdShortName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getWssdShortName() const noexcept
{
    return wssdShortName_;
}
void WssdRegistry::setWssdShortName(const std::string &pWssdShortName) noexcept
{
    wssdShortName_ = std::make_shared<std::string>(pWssdShortName);
    dirtyFlag_[1] = true;
}
void WssdRegistry::setWssdShortName(std::string &&pWssdShortName) noexcept
{
    wssdShortName_ = std::make_shared<std::string>(std::move(pWssdShortName));
    dirtyFlag_[1] = true;
}
void WssdRegistry::setWssdShortNameToNull() noexcept
{
    wssdShortName_.reset();
    dirtyFlag_[1] = true;
}

const std::string &WssdRegistry::getValueOfUssdCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ussdCode_)
        return *ussdCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getUssdCode() const noexcept
{
    return ussdCode_;
}
void WssdRegistry::setUssdCode(const std::string &pUssdCode) noexcept
{
    ussdCode_ = std::make_shared<std::string>(pUssdCode);
    dirtyFlag_[2] = true;
}
void WssdRegistry::setUssdCode(std::string &&pUssdCode) noexcept
{
    ussdCode_ = std::make_shared<std::string>(std::move(pUssdCode));
    dirtyFlag_[2] = true;
}
void WssdRegistry::setUssdCodeToNull() noexcept
{
    ussdCode_.reset();
    dirtyFlag_[2] = true;
}

const std::string &WssdRegistry::getValueOfDisplayTitle() const noexcept
{
    static const std::string defaultValue = std::string();
    if(displayTitle_)
        return *displayTitle_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getDisplayTitle() const noexcept
{
    return displayTitle_;
}
void WssdRegistry::setDisplayTitle(const std::string &pDisplayTitle) noexcept
{
    displayTitle_ = std::make_shared<std::string>(pDisplayTitle);
    dirtyFlag_[3] = true;
}
void WssdRegistry::setDisplayTitle(std::string &&pDisplayTitle) noexcept
{
    displayTitle_ = std::make_shared<std::string>(std::move(pDisplayTitle));
    dirtyFlag_[3] = true;
}
void WssdRegistry::setDisplayTitleToNull() noexcept
{
    displayTitle_.reset();
    dirtyFlag_[3] = true;
}

const std::string &WssdRegistry::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getDescription() const noexcept
{
    return description_;
}
void WssdRegistry::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[4] = true;
}
void WssdRegistry::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[4] = true;
}
void WssdRegistry::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &WssdRegistry::getValueOfActivatedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(activatedOn_)
        return *activatedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WssdRegistry::getActivatedOn() const noexcept
{
    return activatedOn_;
}
void WssdRegistry::setActivatedOn(const ::trantor::Date &pActivatedOn) noexcept
{
    activatedOn_ = std::make_shared<::trantor::Date>(pActivatedOn);
    dirtyFlag_[5] = true;
}
void WssdRegistry::setActivatedOnToNull() noexcept
{
    activatedOn_.reset();
    dirtyFlag_[5] = true;
}

const std::string &WssdRegistry::getValueOfLogoUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(logoUrl_)
        return *logoUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getLogoUrl() const noexcept
{
    return logoUrl_;
}
void WssdRegistry::setLogoUrl(const std::string &pLogoUrl) noexcept
{
    logoUrl_ = std::make_shared<std::string>(pLogoUrl);
    dirtyFlag_[6] = true;
}
void WssdRegistry::setLogoUrl(std::string &&pLogoUrl) noexcept
{
    logoUrl_ = std::make_shared<std::string>(std::move(pLogoUrl));
    dirtyFlag_[6] = true;
}
void WssdRegistry::setLogoUrlToNull() noexcept
{
    logoUrl_.reset();
    dirtyFlag_[6] = true;
}

const int32_t &WssdRegistry::getValueOfTenantId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(tenantId_)
        return *tenantId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WssdRegistry::getTenantId() const noexcept
{
    return tenantId_;
}
void WssdRegistry::setTenantId(const int32_t &pTenantId) noexcept
{
    tenantId_ = std::make_shared<int32_t>(pTenantId);
    dirtyFlag_[7] = true;
}

const int32_t &WssdRegistry::getValueOfServiceType() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(serviceType_)
        return *serviceType_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WssdRegistry::getServiceType() const noexcept
{
    return serviceType_;
}
void WssdRegistry::setServiceType(const int32_t &pServiceType) noexcept
{
    serviceType_ = std::make_shared<int32_t>(pServiceType);
    dirtyFlag_[8] = true;
}

const int32_t &WssdRegistry::getValueOfRank() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(rank_)
        return *rank_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WssdRegistry::getRank() const noexcept
{
    return rank_;
}
void WssdRegistry::setRank(const int32_t &pRank) noexcept
{
    rank_ = std::make_shared<int32_t>(pRank);
    dirtyFlag_[9] = true;
}

const std::string &WssdRegistry::getValueOfMerchantIdentifier() const noexcept
{
    static const std::string defaultValue = std::string();
    if(merchantIdentifier_)
        return *merchantIdentifier_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getMerchantIdentifier() const noexcept
{
    return merchantIdentifier_;
}
void WssdRegistry::setMerchantIdentifier(const std::string &pMerchantIdentifier) noexcept
{
    merchantIdentifier_ = std::make_shared<std::string>(pMerchantIdentifier);
    dirtyFlag_[10] = true;
}
void WssdRegistry::setMerchantIdentifier(std::string &&pMerchantIdentifier) noexcept
{
    merchantIdentifier_ = std::make_shared<std::string>(std::move(pMerchantIdentifier));
    dirtyFlag_[10] = true;
}
void WssdRegistry::setMerchantIdentifierToNull() noexcept
{
    merchantIdentifier_.reset();
    dirtyFlag_[10] = true;
}

const std::string &WssdRegistry::getValueOfCategory() const noexcept
{
    static const std::string defaultValue = std::string();
    if(category_)
        return *category_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getCategory() const noexcept
{
    return category_;
}
void WssdRegistry::setCategory(const std::string &pCategory) noexcept
{
    category_ = std::make_shared<std::string>(pCategory);
    dirtyFlag_[11] = true;
}
void WssdRegistry::setCategory(std::string &&pCategory) noexcept
{
    category_ = std::make_shared<std::string>(std::move(pCategory));
    dirtyFlag_[11] = true;
}
void WssdRegistry::setCategoryToNull() noexcept
{
    category_.reset();
    dirtyFlag_[11] = true;
}

const std::string &WssdRegistry::getValueOfBusinessName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(businessName_)
        return *businessName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getBusinessName() const noexcept
{
    return businessName_;
}
void WssdRegistry::setBusinessName(const std::string &pBusinessName) noexcept
{
    businessName_ = std::make_shared<std::string>(pBusinessName);
    dirtyFlag_[12] = true;
}
void WssdRegistry::setBusinessName(std::string &&pBusinessName) noexcept
{
    businessName_ = std::make_shared<std::string>(std::move(pBusinessName));
    dirtyFlag_[12] = true;
}
void WssdRegistry::setBusinessNameToNull() noexcept
{
    businessName_.reset();
    dirtyFlag_[12] = true;
}

const std::string &WssdRegistry::getValueOfExecutable() const noexcept
{
    static const std::string defaultValue = std::string();
    if(executable_)
        return *executable_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WssdRegistry::getExecutable() const noexcept
{
    return executable_;
}
void WssdRegistry::setExecutable(const std::string &pExecutable) noexcept
{
    executable_ = std::make_shared<std::string>(pExecutable);
    dirtyFlag_[13] = true;
}
void WssdRegistry::setExecutable(std::string &&pExecutable) noexcept
{
    executable_ = std::make_shared<std::string>(std::move(pExecutable));
    dirtyFlag_[13] = true;
}
void WssdRegistry::setExecutableToNull() noexcept
{
    executable_.reset();
    dirtyFlag_[13] = true;
}

const ::trantor::Date &WssdRegistry::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WssdRegistry::getCreatedAt() const noexcept
{
    return createdAt_;
}
void WssdRegistry::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[14] = true;
}
void WssdRegistry::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[14] = true;
}

const ::trantor::Date &WssdRegistry::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WssdRegistry::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void WssdRegistry::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[15] = true;
}
void WssdRegistry::setUpdatedAtToNull() noexcept
{
    updatedAt_.reset();
    dirtyFlag_[15] = true;
}

void WssdRegistry::updateId(const uint64_t id)
{
}

const std::vector<std::string> &WssdRegistry::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "wssd_short_name",
        "ussd_code",
        "display_title",
        "description",
        "activated_on",
        "logo_url",
        "tenant_id",
        "service_type",
        "rank",
        "merchant_identifier",
        "category",
        "business_name",
        "executable",
        "created_at",
        "updated_at"
    };
    return inCols;
}

void WssdRegistry::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getWssdShortName())
        {
            binder << getValueOfWssdShortName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUssdCode())
        {
            binder << getValueOfUssdCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDisplayTitle())
        {
            binder << getValueOfDisplayTitle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getActivatedOn())
        {
            binder << getValueOfActivatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLogoUrl())
        {
            binder << getValueOfLogoUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTenantId())
        {
            binder << getValueOfTenantId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getServiceType())
        {
            binder << getValueOfServiceType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getRank())
        {
            binder << getValueOfRank();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getMerchantIdentifier())
        {
            binder << getValueOfMerchantIdentifier();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCategory())
        {
            binder << getValueOfCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getBusinessName())
        {
            binder << getValueOfBusinessName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getExecutable())
        {
            binder << getValueOfExecutable();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> WssdRegistry::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    if(dirtyFlag_[15])
    {
        ret.push_back(getColumnName(15));
    }
    return ret;
}

void WssdRegistry::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getWssdShortName())
        {
            binder << getValueOfWssdShortName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUssdCode())
        {
            binder << getValueOfUssdCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDisplayTitle())
        {
            binder << getValueOfDisplayTitle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getActivatedOn())
        {
            binder << getValueOfActivatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLogoUrl())
        {
            binder << getValueOfLogoUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTenantId())
        {
            binder << getValueOfTenantId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getServiceType())
        {
            binder << getValueOfServiceType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getRank())
        {
            binder << getValueOfRank();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getMerchantIdentifier())
        {
            binder << getValueOfMerchantIdentifier();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCategory())
        {
            binder << getValueOfCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getBusinessName())
        {
            binder << getValueOfBusinessName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getExecutable())
        {
            binder << getValueOfExecutable();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value WssdRegistry::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getWssdShortName())
    {
        ret["wssd_short_name"]=getValueOfWssdShortName();
    }
    else
    {
        ret["wssd_short_name"]=Json::Value();
    }
    if(getUssdCode())
    {
        ret["ussd_code"]=getValueOfUssdCode();
    }
    else
    {
        ret["ussd_code"]=Json::Value();
    }
    if(getDisplayTitle())
    {
        ret["display_title"]=getValueOfDisplayTitle();
    }
    else
    {
        ret["display_title"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getActivatedOn())
    {
        ret["activated_on"]=getActivatedOn()->toDbStringLocal();
    }
    else
    {
        ret["activated_on"]=Json::Value();
    }
    if(getLogoUrl())
    {
        ret["logo_url"]=getValueOfLogoUrl();
    }
    else
    {
        ret["logo_url"]=Json::Value();
    }
    if(getTenantId())
    {
        ret["tenant_id"]=getValueOfTenantId();
    }
    else
    {
        ret["tenant_id"]=Json::Value();
    }
    if(getServiceType())
    {
        ret["service_type"]=getValueOfServiceType();
    }
    else
    {
        ret["service_type"]=Json::Value();
    }
    if(getRank())
    {
        ret["rank"]=getValueOfRank();
    }
    else
    {
        ret["rank"]=Json::Value();
    }
    if(getMerchantIdentifier())
    {
        ret["merchant_identifier"]=getValueOfMerchantIdentifier();
    }
    else
    {
        ret["merchant_identifier"]=Json::Value();
    }
    if(getCategory())
    {
        ret["category"]=getValueOfCategory();
    }
    else
    {
        ret["category"]=Json::Value();
    }
    if(getBusinessName())
    {
        ret["business_name"]=getValueOfBusinessName();
    }
    else
    {
        ret["business_name"]=Json::Value();
    }
    if(getExecutable())
    {
        ret["executable"]=getValueOfExecutable();
    }
    else
    {
        ret["executable"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string WssdRegistry::toString() const
{
    return toJson().toStyledString();
}

Json::Value WssdRegistry::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 16)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getWssdShortName())
            {
                ret[pMasqueradingVector[1]]=getValueOfWssdShortName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUssdCode())
            {
                ret[pMasqueradingVector[2]]=getValueOfUssdCode();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDisplayTitle())
            {
                ret[pMasqueradingVector[3]]=getValueOfDisplayTitle();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[4]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getActivatedOn())
            {
                ret[pMasqueradingVector[5]]=getActivatedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getLogoUrl())
            {
                ret[pMasqueradingVector[6]]=getValueOfLogoUrl();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getTenantId())
            {
                ret[pMasqueradingVector[7]]=getValueOfTenantId();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getServiceType())
            {
                ret[pMasqueradingVector[8]]=getValueOfServiceType();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getRank())
            {
                ret[pMasqueradingVector[9]]=getValueOfRank();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getMerchantIdentifier())
            {
                ret[pMasqueradingVector[10]]=getValueOfMerchantIdentifier();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCategory())
            {
                ret[pMasqueradingVector[11]]=getValueOfCategory();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getBusinessName())
            {
                ret[pMasqueradingVector[12]]=getValueOfBusinessName();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getExecutable())
            {
                ret[pMasqueradingVector[13]]=getValueOfExecutable();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[14]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[15].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[15]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[15]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getWssdShortName())
    {
        ret["wssd_short_name"]=getValueOfWssdShortName();
    }
    else
    {
        ret["wssd_short_name"]=Json::Value();
    }
    if(getUssdCode())
    {
        ret["ussd_code"]=getValueOfUssdCode();
    }
    else
    {
        ret["ussd_code"]=Json::Value();
    }
    if(getDisplayTitle())
    {
        ret["display_title"]=getValueOfDisplayTitle();
    }
    else
    {
        ret["display_title"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getActivatedOn())
    {
        ret["activated_on"]=getActivatedOn()->toDbStringLocal();
    }
    else
    {
        ret["activated_on"]=Json::Value();
    }
    if(getLogoUrl())
    {
        ret["logo_url"]=getValueOfLogoUrl();
    }
    else
    {
        ret["logo_url"]=Json::Value();
    }
    if(getTenantId())
    {
        ret["tenant_id"]=getValueOfTenantId();
    }
    else
    {
        ret["tenant_id"]=Json::Value();
    }
    if(getServiceType())
    {
        ret["service_type"]=getValueOfServiceType();
    }
    else
    {
        ret["service_type"]=Json::Value();
    }
    if(getRank())
    {
        ret["rank"]=getValueOfRank();
    }
    else
    {
        ret["rank"]=Json::Value();
    }
    if(getMerchantIdentifier())
    {
        ret["merchant_identifier"]=getValueOfMerchantIdentifier();
    }
    else
    {
        ret["merchant_identifier"]=Json::Value();
    }
    if(getCategory())
    {
        ret["category"]=getValueOfCategory();
    }
    else
    {
        ret["category"]=Json::Value();
    }
    if(getBusinessName())
    {
        ret["business_name"]=getValueOfBusinessName();
    }
    else
    {
        ret["business_name"]=Json::Value();
    }
    if(getExecutable())
    {
        ret["executable"]=getValueOfExecutable();
    }
    else
    {
        ret["executable"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool WssdRegistry::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("wssd_short_name"))
    {
        if(!validJsonOfField(1, "wssd_short_name", pJson["wssd_short_name"], err, true))
            return false;
    }
    if(pJson.isMember("ussd_code"))
    {
        if(!validJsonOfField(2, "ussd_code", pJson["ussd_code"], err, true))
            return false;
    }
    if(pJson.isMember("display_title"))
    {
        if(!validJsonOfField(3, "display_title", pJson["display_title"], err, true))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("activated_on"))
    {
        if(!validJsonOfField(5, "activated_on", pJson["activated_on"], err, true))
            return false;
    }
    if(pJson.isMember("logo_url"))
    {
        if(!validJsonOfField(6, "logo_url", pJson["logo_url"], err, true))
            return false;
    }
    if(pJson.isMember("tenant_id"))
    {
        if(!validJsonOfField(7, "tenant_id", pJson["tenant_id"], err, true))
            return false;
    }
    else
    {
        err="The tenant_id column cannot be null";
        return false;
    }
    if(pJson.isMember("service_type"))
    {
        if(!validJsonOfField(8, "service_type", pJson["service_type"], err, true))
            return false;
    }
    if(pJson.isMember("rank"))
    {
        if(!validJsonOfField(9, "rank", pJson["rank"], err, true))
            return false;
    }
    if(pJson.isMember("merchant_identifier"))
    {
        if(!validJsonOfField(10, "merchant_identifier", pJson["merchant_identifier"], err, true))
            return false;
    }
    if(pJson.isMember("category"))
    {
        if(!validJsonOfField(11, "category", pJson["category"], err, true))
            return false;
    }
    if(pJson.isMember("business_name"))
    {
        if(!validJsonOfField(12, "business_name", pJson["business_name"], err, true))
            return false;
    }
    if(pJson.isMember("executable"))
    {
        if(!validJsonOfField(13, "executable", pJson["executable"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(14, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(15, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool WssdRegistry::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 16)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[15].empty())
      {
          if(pJson.isMember(pMasqueradingVector[15]))
          {
              if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WssdRegistry::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("wssd_short_name"))
    {
        if(!validJsonOfField(1, "wssd_short_name", pJson["wssd_short_name"], err, false))
            return false;
    }
    if(pJson.isMember("ussd_code"))
    {
        if(!validJsonOfField(2, "ussd_code", pJson["ussd_code"], err, false))
            return false;
    }
    if(pJson.isMember("display_title"))
    {
        if(!validJsonOfField(3, "display_title", pJson["display_title"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("activated_on"))
    {
        if(!validJsonOfField(5, "activated_on", pJson["activated_on"], err, false))
            return false;
    }
    if(pJson.isMember("logo_url"))
    {
        if(!validJsonOfField(6, "logo_url", pJson["logo_url"], err, false))
            return false;
    }
    if(pJson.isMember("tenant_id"))
    {
        if(!validJsonOfField(7, "tenant_id", pJson["tenant_id"], err, false))
            return false;
    }
    if(pJson.isMember("service_type"))
    {
        if(!validJsonOfField(8, "service_type", pJson["service_type"], err, false))
            return false;
    }
    if(pJson.isMember("rank"))
    {
        if(!validJsonOfField(9, "rank", pJson["rank"], err, false))
            return false;
    }
    if(pJson.isMember("merchant_identifier"))
    {
        if(!validJsonOfField(10, "merchant_identifier", pJson["merchant_identifier"], err, false))
            return false;
    }
    if(pJson.isMember("category"))
    {
        if(!validJsonOfField(11, "category", pJson["category"], err, false))
            return false;
    }
    if(pJson.isMember("business_name"))
    {
        if(!validJsonOfField(12, "business_name", pJson["business_name"], err, false))
            return false;
    }
    if(pJson.isMember("executable"))
    {
        if(!validJsonOfField(13, "executable", pJson["executable"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(14, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(15, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool WssdRegistry::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 16)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
      if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
      {
          if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WssdRegistry::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 25)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 25)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 250)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 250)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 300)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 300)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 80)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 80)";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 60)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 60)";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 15:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
